# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "테스트플라이트에 최신코드의 오늘뭐임 iOS앱을 올려요"
  lane :testflight_release do |options|
    version = options[:version]

    info_plist_path = "./Projects/App/iOS/Support/Info.plist"
    build_number = get_info_plist_value(path: info_plist_path, key: "CFBundleVersion")
    prev_version = get_info_plist_value(path: info_plist_path, key: "CFBundleShortVersionString")
    set_info_plist_value(path: info_plist_path, key: "CFBundleVersion", value: "#{build_number.to_i + 1}")
    set_info_plist_value(path: info_plist_path, key: "CFBundleShortVersionString", value: version)

    discord_notifier(
      webhook_url: ENV["WEBHOOK_URL"],
      title: "💫 오늘뭐임 iOS TestFlight 업로드 자동화 시작",
      thumbnail_url: "https://github.com/baekteun/TodayWhat-new/assets/74440939/20913d7a-59a6-46b5-b3e2-c6456a08a7e1",
      color: "FFF500",
      description: "오늘뭐임 iOS #{version}을 테스트플라이트 업로드를 시작해요 !"
    )
    build_app(
      scheme: "TodayWhat",
      configuration: "STAGE"
    )
    upload_to_testflight(
      api_key_path: "fastlane/AppStoreAPIKey.json"
    )
    set_info_plist_value(path: info_plist_path, key: "CFBundleShortVersionString", value: prev_version)
    discord_notifier(
      webhook_url: ENV["WEBHOOK_URL"],
      title: "🚀 오늘뭐임 iOS TestFlight 업로드 자동화 성공",
      thumbnail_url: "https://github.com/baekteun/TodayWhat-new/assets/74440939/842b2d8e-0219-42b3-95c7-5ec60a85f863",
      color: "69B353",
      description: "오늘뭐임 iOS #{version}을 테스트플라이트 성공적으로 업로드하였어요 !"
    )
  end

  desc "앱스토어에 오늘뭐임 iOS앱의 새로운 버전 심사를 올려요"
  lane :appstore_release do |options|
    version = options[:version]

    info_plist_path = "./Projects/App/iOS/Support/Info.plist"
    build_number = get_info_plist_value(path: info_plist_path, key: "CFBundleVersion")
    set_info_plist_value(path: info_plist_path, key: "CFBundleVersion", value: "#{build_number.to_i + 1}")
    set_info_plist_value(path: info_plist_path, key: "CFBundleShortVersionString", value: version)

    discord_notifier(
      webhook_url: ENV["WEBHOOK_URL"],
      title: "💫 오늘뭐임 iOS 배포 자동화 시작",
      thumbnail_url: "https://github.com/baekteun/TodayWhat-new/assets/74440939/20913d7a-59a6-46b5-b3e2-c6456a08a7e1",
      color: "FFF500",
      description: "오늘뭐임 iOS #{version}을 앱스토어 배포를 시작해요 !"
    )

    build_app(
      scheme: "TodayWhat",
      configuration: "PROD",
      export_method: "app-store"
    )
    upload_to_app_store(
      app_version: version,
      submit_for_review: true,
      force: true,
      automatic_release: true,
      skip_metadata: false,
      api_key_path: "fastlane/AppStoreAPIKey.json",
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
    discord_notifier(
      webhook_url: ENV["WEBHOOK_URL"],
      title: "🚀 오늘뭐임 iOS 배포 자동화 성공",
      thumbnail_url: "https://github.com/baekteun/TodayWhat-new/assets/74440939/842b2d8e-0219-42b3-95c7-5ec60a85f863",
      color: "69B353",
      description: "오늘뭐임 iOS #{version}을 앱스토어에 성공적으로 배포하였습니다 !"
    )
    set_github_release(
      repository_name: "baegteun/TodayWhat-iOS",
      api_token: ENV["GITHUB_TOKEN"],
      name: "오늘뭐임 iOS #{version}",
      tag_name: "#{version}-iOS",
      commitish: "master",
      description: (File.read("metadata/ko/release_notes.txt") rescue ""),
      is_generate_release_notes: true
    )
  end

  error do |lane, exception, options|
    discord_notifier(
      webhook_url: ENV["WEBHOOK_URL"],
      title: "👾 오늘뭐임 iOS 배포 자동화 실패..",
      thumbnail_url: "https://github.com/baekteun/TodayWhat-new/assets/74440939/87dbdea4-2499-41c8-9b71-a19922c56707",
      success: false,
      color: "#BB3639",
      description: "#{exception}"
    )
  end
end

platform :mac do
  desc "테스트플라이트에 최신코드의 오늘뭐임 macOS앱을 올려요"
  lane :testflight_release do |options|
    version = options[:version]

    info_plist_path = "./Projects/App/macOS/Support/Info.plist"
    build_number = get_info_plist_value(path: info_plist_path, key: "CFBundleVersion")
    prev_version = get_info_plist_value(path: info_plist_path, key: "CFBundleShortVersionString")
    set_info_plist_value(path: info_plist_path, key: "CFBundleVersion", value: "#{build_number.to_i + 1}")
    set_info_plist_value(path: info_plist_path, key: "CFBundleShortVersionString", value: version)

    discord_notifier(
      webhook_url: ENV["WEBHOOK_URL"],
      title: "💫 오늘뭐임 macOS TestFlight 업로드 자동화 시작",
      thumbnail_url: "https://github.com/baekteun/TodayWhat-new/assets/74440939/20913d7a-59a6-46b5-b3e2-c6456a08a7e1",
      color: "FFF500",
      description: "오늘뭐임 macOS #{version}을 테스트플라이트 업로드를 시작해요 !"
    )
    build_app(
      scheme: "TodayWhat-MacOS",
      configuration: "STAGE"
    )
    upload_to_testflight(
      api_key_path: "fastlane/AppStoreAPIKey.json"
    )
    set_info_plist_value(path: info_plist_path, key: "CFBundleShortVersionString", value: prev_version)
    discord_notifier(
      webhook_url: ENV["WEBHOOK_URL"],
      title: "🚀 오늘뭐임 macOS TestFlight 업로드 자동화 성공",
      thumbnail_url: "https://github.com/baekteun/TodayWhat-new/assets/74440939/842b2d8e-0219-42b3-95c7-5ec60a85f863",
      color: "69B353",
      description: "오늘뭐임 macOS #{version}을 테스트플라이트 성공적으로 업로드하였습니다 !"
    )
  end

  desc "앱스토어에 오늘뭐임 macOS앱의 새로운 버전 심사를 올려요"
  lane :appstore_release do |options|
    version = options[:version]

    info_plist_path = "./Projects/App/macOS/Support/Info.plist"
    build_number = get_info_plist_value(path: info_plist_path, key: "CFBundleVersion")
    set_info_plist_value(path: info_plist_path, key: "CFBundleVersion", value: "#{build_number.to_i + 1}")
    set_info_plist_value(path: info_plist_path, key: "CFBundleShortVersionString", value: version)

    discord_notifier(
      webhook_url: ENV["WEBHOOK_URL"],
      title: "💫 오늘뭐임 macOS 앱스토어 배포 자동화 시작",
      thumbnail_url: "https://github.com/baekteun/TodayWhat-new/assets/74440939/20913d7a-59a6-46b5-b3e2-c6456a08a7e1",
      color: "FFF500",
      description: "오늘뭐임 macOS #{version}을 앱스토어 배포를 시작해요 !"
    )
    build_app(
      scheme: "TodayWhat-MacOS",
      configuration: "PROD",
      export_method: "app-store"
    )
    upload_to_app_store(
      app_version: version,
      submit_for_review: true,
      force: true,
      automatic_release: true,
      skip_metadata: false,
      api_key_path: "fastlane/AppStoreAPIKey.json",
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
    discord_notifier(
      webhook_url: ENV["WEBHOOK_URL"],
      title: "🚀 오늘뭐임 macOS 배포 자동화 성공",
      thumbnail_url: "https://github.com/baekteun/TodayWhat-new/assets/74440939/842b2d8e-0219-42b3-95c7-5ec60a85f863",
      color: "69B353",
      description: "오늘뭐임 macOS #{version}을 앱스토어에 성공적으로 배포하였습니다 !"
    )
    set_github_release(
      repository_name: "baegteun/TodayWhat-new",
      api_token: ENV["GITHUB_TOKEN"],
      name: "오늘뭐임 macOS #{version}",
      tag_name: "#{version}-MacOS",
      commitish: "master",
      description: (File.read("metadata/ko/release_notes.txt") rescue ""),
      is_generate_release_notes: true
    )
  end

  error do |lane, exception, options|
    discord_notifier(
      webhook_url: ENV["WEBHOOK_URL"],
      title: "👾 오늘뭐임 macOS 배포 자동화 실패..",
      thumbnail_url: "https://github.com/baekteun/TodayWhat-new/assets/74440939/87dbdea4-2499-41c8-9b71-a19922c56707",
      success: false,
      color: "#BB3639",
      description: "#{exception}"
    )
  end
end