name: Cleanup Upload Branches
# Xcode Cloud에서 upload 로 시작하는 브랜치가 변경될 시 QA 빌드를 올리는 Xcode Cloud워크플로가 있음.
# 더미용 브랜치를 하루마다 제거하는 GitHub Action workflow

on:
  schedule:
    - cron: "0 23 * * *" # 매일 오전 8시에 실행 (UTC 기준이기에 +9)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete upload/* branches
        uses: ./.github/actions/delete_branches/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: upload
