name: TestFlight Beta

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: "Platform to deploy"
        options:
          - ios
          - mac
        default: ios
        required: true
      version:
        description: "Version to upload to TestFlight"
        required: true

env:
  KEYCHAIN: ${{ 'todaywhat.keychain' }}
  CERTS_EXPORT_PWD: ${{ secrets.CERTS_EXPORT_PWD }}

  XCCONFIG_SECRET: ${{ secrets.XCCONFIG_SECRET }}
  ENCRYPTED_XCCONFIG_PATH: ${{ 'XCConfig.zip.gpg' }}
  DECRYPTED_XCCONFIG_PATH: ${{ 'XCConfig.zip' }}

  IOS_GOOGLE_SERVICE_PLIST_SECRET: ${{ secrets.GOOGLE_SERVICE_PLIST_SECRET }}
  ENCRYPTED_IOS_GOOGLE_SERVICE_PLIST_PATH: ${{ 'Projects/App/iOS/Resources/GoogleService-Info.plist.gpg' }}
  DECRYPTED_IOS_GOOGLE_SERVICE_PLIST_PATH: ${{ 'Projects/App/iOS/Resources/GoogleService-Info.plist' }}

  FASTLANE_SECRET: ${{ secrets.FASTLANE_SECRET }}
  ENCRYPTED_FASTLANE_ENV_PATH: ${{ 'fastlane/.env.default.gpg' }}
  DECRYPTED_FASTLANE_ENV_PATH: ${{ 'fastlane/.env.default' }}

  APPSTORE_CONNECT_SECRET: ${{ secrets.APPSTORE_CONNECT_SECRET }}
  ENCRYPTED_APPSTORE_CONNECT_PATH: ${{ 'fastlane/AppStoreAPIKey.json.gpg' }}
  DECRYPTED_APPSTORE_CONNECT_PATH: ${{ 'fastlane/AppStoreAPIKey.json' }}

jobs:
  distribute:
    name: 🚀 TestFlight Upload
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}

      - name: Decode encrypted files
        run: |
          sh .github/workflows/AppStore/Decode.sh
          sh .github/workflows/AppStore/Keychain.sh
        shell: bash
        env:
          KEYCHAIN: "todaywhat.keychain"

      - uses: jdx/mise-action@v2

      - name: Install tuist
        run: |
          mise install tuist

      - name: Install fastlane
        run: brew install fastlane

      - name: Install dependencies
        run: tuist install

      - name: Project generate
        run: TUIST_ENV=CD tuist generate

      - name: Release Branch Create
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config pull.rebase false
          git checkout -b build-number-increase-for-testflight

      - name: Distribute
        run: sh .github/workflows/TestFlight/TestFlight.sh
        shell: bash
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSPHRASE }}
          PLATFORM: ${{ github.event.inputs.platform }}
          VERSION: ${{ github.event.inputs.version }}

      - name: Commit and PR
        run: sh .github/workflows/TestFlight/BuildNumberIncreasePR.sh
        shell: bash
        env:
          VERSION: ${{ github.event.inputs.version }}
          GH_TOKEN: ${{ github.token }}
